package eu.monnetproject.clesa.core.tokenizer.latin;

/* Generated By:JavaCC: Do not edit this line. LatinTokenizerCCConstants.java */


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LatinTokenizerCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALPHANUM = 1;
  /** RegularExpression Id. */
  int APOSTROPHE = 2;
  /** RegularExpression Id. */
  int ACRONYM = 3;
  /** RegularExpression Id. */
  int COMPANY = 4;
  /** RegularExpression Id. */
  int EMAIL = 5;
  /** RegularExpression Id. */
  int HOST = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int PUNC = 8;
  /** RegularExpression Id. */
  int ABB = 9;
  /** RegularExpression Id. */
  int DIPL = 10;
  /** RegularExpression Id. */
  int P = 11;
  /** RegularExpression Id. */
  int HAS_DIGIT = 12;
  /** RegularExpression Id. */
  int ALPHA = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int CJK = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int ABBREV = 17;
  /** RegularExpression Id. */
  int NOISE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ALPHANUM>",
    "<APOSTROPHE>",
    "<ACRONYM>",
    "<COMPANY>",
    "<EMAIL>",
    "<HOST>",
    "<NUM>",
    "<PUNC>",
    "<ABB>",
    "<DIPL>",
    "<P>",
    "<HAS_DIGIT>",
    "<ALPHA>",
    "<LETTER>",
    "<CJK>",
    "<DIGIT>",
    "<ABBREV>",
    "<NOISE>",
  };

}
